export const SECTIONS = [
  {
    id: 'hero',
    title: 'Ahmed\nMassoud',
    subtitle: 'Product Designer',
    description: "I'm a UI Designer with over 5 years of experience, with an eye for pixel-perfect designs and a deep understanding of the Saudi digital landscape.",
    email: 'a7medmass3oud@gmail.com',
  },
  {
    id: 'about',
    title: 'About Me',
    subtitle: '',
    description: "Having worked extensively on governmental projects in Saudi Arabia, I specialize in creating seamless, user-centric experiences that align with the region's unique needs and regulations. My expertise lies in compliance, accessibility, and efficiency for enterprise platforms.",
    items: [
      { company: 'Tawuniya', role: 'Senior Product Designer', period: 'Sep 2025 \u2014 Current', logo: '/tawuniya.svg' },
      { company: 'Tremoloo', role: 'Product Designer', period: 'Apr 2023 \u2014 Aug 2025', logo: '/tremoloo.svg' },
      { company: 'Anspire', role: 'Product Designer', period: 'Feb 2022 \u2014 Mar 2023', logo: '/anspire.svg' },
    ],
  },
  {
    id: 'projects',
    title: 'Featured\nProjects',
    subtitle: 'Strategic Digital Ecosystems.',
    description: "A look at what I've been building lately",
    projects: [
      {
        name: 'Zedesh Footer',
        category: 'Web Design',
        description: 'Modern corporate website footer design.',
        image: 'https://cdn.dribbble.com/userupload/46953927/file/c77a6be205a4058df8a99fa57026f474.png',
      },
      {
        name: 'Zedesh – Hero',
        category: 'Web Design',
        description: 'Modern corporate website hero section.',
        image: 'https://cdn.dribbble.com/userupload/46953898/file/5d888fc5ba7548dbad4addf4fc88848b.png',
      },
      {
        name: 'Zedesh – Overview',
        category: 'Web Design',
        description: 'Modern corporate website design.',
        image: 'https://cdn.dribbble.com/userupload/46953830/file/26d1b28ec393141d91117d9fb8d14d84.png',
      },
      {
        name: 'AI SaaS Landing Page',
        category: 'Landing Page',
        description: 'Dark futuristic AI SaaS design exploration.',
        image: 'https://cdn.dribbble.com/userupload/45307253/file/c67bec43e0525a9d1a2711277a94542f.png',
      },
      {
        name: 'Cinematic AI Hero',
        category: 'Landing Page',
        description: 'Cinematic AI hero landing page.',
        image: 'https://cdn.dribbble.com/userupload/43705307/file/original-c17ee9fca86f483c8474732acbbbd3e2.png',
      },
      {
        name: 'Zoo – Landing Page',
        category: 'Landing Page',
        description: 'Cinematic landing page concept.',
        image: 'https://cdn.dribbble.com/userupload/43669888/file/still-ecf7d8a49293308bff8ee3eecf90def9.png',
      },
      {
        name: 'Anubis Landing Page',
        category: 'Landing Page',
        description: 'Cinematic Egyptian-themed web design.',
        image: 'https://cdn.dribbble.com/userupload/43547648/file/original-249ad224123ec7fc821841271f4536fa.png',
      },
      {
        name: 'Logistics Platform',
        category: 'Product UI',
        description: 'Hero section for a modern logistics platform.',
        image: 'https://cdn.dribbble.com/userupload/43503355/file/still-05746b2ddbe7bb39a4e84abf1bdb1082.png',
      },
      {
        name: 'Tactical Fighter UI',
        category: 'Game UI',
        description: 'Character customization UI for tactical fighting game.',
        image: 'https://cdn.dribbble.com/userupload/43499301/file/original-a470d3213a0cceded6ba5f083e1270ee.png',
      },
      {
        name: '404 – Mission Not Found',
        category: 'Web Design',
        description: 'Ninja-themed 404 error page.',
        image: 'https://cdn.dribbble.com/userupload/43488691/file/original-c0819d7ef6c59f1707445b328ec5c27b.png',
      },
      {
        name: 'Jungle Fighter UI',
        category: 'Game UI',
        description: 'Character customization UI – Jungle Fighter.',
        image: 'https://cdn.dribbble.com/userupload/43488677/file/original-d0d6b8a5f8046cfcfecccfecce90448c.png',
      },
      {
        name: 'VALORANT Agent Screen',
        category: 'Game UI',
        description: 'VALORANT agent screen concept.',
        image: 'https://cdn.dribbble.com/userupload/43378002/file/original-961b3996385c5711be1b2d2f228d5804.png',
      },
      {
        name: 'Valorant – Breach',
        category: 'Game UI',
        description: 'Valorant character page concept for Breach.',
        image: 'https://cdn.dribbble.com/userupload/43330155/file/original-6557e165746fe23885ff0fcf4ba72716.png',
      },
      {
        name: 'Valorant – Viper',
        category: 'Game UI',
        description: 'Viper character page concept.',
        image: 'https://cdn.dribbble.com/userupload/43316986/file/original-4c3de0a98ce242e7235020d2793bb657.png',
      },
    ],
  },
  {
    id: 'contact',
    title: 'Get In Touch',
    subtitle: "Let's build the next generation of digital tools.",
    email: 'a7medmass3oud@gmail.com',
    whatsapp: '01151029852',
    socials: ['LinkedIn', 'Dribbble', 'WhatsApp'],
  },
];
